import type { SystemAnalysis } from '../capacity'
import { fmtUsers } from '../capacity'
import type { GlobalAssumptions } from '../types'

function rps(n: number | null): string {
  if (n == null) return '—'
  if (n >= 1000) return `${(n / 1000).toFixed(n >= 10000 ? 0 : 1)}k req/s`
  return `${Math.round(n)} req/s`
}

export function buildReportMarkdown(name: string, a: SystemAnalysis, g: GlobalAssumptions): string {
  const lines: string[] = []
  lines.push(`# Capacity report — ${name}`)
  lines.push('')
  lines.push(`_Generated by System Designer Studio._`)
  lines.push('')
  lines.push('## Headline')
  lines.push('')
  lines.push(`- **Max concurrent users:** ${fmtUsers(a.maxUsers)}`)
  lines.push(`- **Bottleneck:** ${a.bottleneckLabel ?? 'none (no constrained component on the traffic path)'}`)
  lines.push(`- **Estimated infra cost:** $${a.totalMonthlyCost.toLocaleString()}/month (fixed components; LLM/usage billed separately)`)
  lines.push('')
  lines.push('## Workload assumptions')
  lines.push('')
  lines.push(`- Requests/sec per active user: **${g.rpsPerUser}**`)
  lines.push(`- Peak-to-average multiplier: **${g.peakRatio}×**`)
  lines.push(`- Write ratio: **${Math.round(g.writeRatio * 100)}%**`)
  lines.push(`- Reference target users: **${g.targetUsers.toLocaleString()}**`)
  lines.push('')
  lines.push(`> Peak load at target = ${g.targetUsers.toLocaleString()} users × ${g.rpsPerUser} × ${g.peakRatio} = **${rps(a.reachablePeakRps)}** entering the system.`)
  lines.push('')
  lines.push('## Per-component analysis')
  lines.push('')
  lines.push('| Component | Type | Capacity | Load @target | Max users | Cost/mo |')
  lines.push('|---|---|---|---|---|---|')
  for (const nd of a.nodes) {
    lines.push(
      `| ${nd.label} | ${nd.type} | ${rps(nd.capacity)} | ${nd.onPath && nd.capacity != null ? Math.round(nd.utilization * 100) + '%' : '—'} | ${
        nd.capacity == null || !nd.onPath ? '—' : fmtUsers(nd.maxUsers)
      } | ${nd.monthlyCost ? '$' + nd.monthlyCost : '—'} |`,
    )
  }
  lines.push('')
  lines.push('### How each capacity was derived')
  lines.push('')
  for (const nd of a.nodes) {
    if (nd.capacity != null) lines.push(`- **${nd.label}** — ${nd.capacityNote}`)
  }
  lines.push('')
  if (a.warnings.length) {
    lines.push('## Warnings')
    lines.push('')
    a.warnings.forEach((w) => lines.push(`- ⚠️ ${w}`))
    lines.push('')
  }
  lines.push('## Method')
  lines.push('')
  lines.push(
    'Per-user peak demand is propagated from each traffic source through the wired graph. ' +
      'A node passes `demand × outflow` to its downstream neighbours, so a cache (hit ratio) reduces what reaches the stores behind it. ' +
      'Each node’s `max users = capacity ÷ per-user demand`; the system maximum is the most constrained node on the path (the bottleneck).',
  )
  lines.push('')
  return lines.join('\n')
}

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Build a complete, standalone, print-optimised HTML document for the report —
 * light theme, real document typography, the diagram embedded. This is what the
 * "Print / PDF" button renders (in an isolated iframe), so the PDF is a proper
 * document rather than a screenshot of the app.
 */
export function buildReportHtml(
  name: string,
  a: SystemAnalysis,
  g: GlobalAssumptions,
  diagramDataUrl?: string,
): string {
  const generated = new Date().toLocaleString()
  const onPath = a.nodes.filter((n) => n.onPath && n.capacity != null).sort((x, y) => y.utilization - x.utilization)

  const utilColor = (u: number) => (u >= 1 ? '#c0392b' : u >= 0.75 ? '#b8860b' : '#2e7d32')

  const rows = a.nodes
    .map(
      (n) => `<tr>
        <td>${esc(n.label)}</td>
        <td class="muted">${esc(n.type)}</td>
        <td class="num">${rps(n.capacity)}</td>
        <td class="num">${n.onPath && n.capacity != null ? Math.round(n.utilization * 100) + '%' : '—'}</td>
        <td class="num">${n.capacity == null || !n.onPath ? '—' : fmtUsers(n.maxUsers)}</td>
        <td class="num">${n.monthlyCost ? '$' + n.monthlyCost.toLocaleString() : '—'}</td>
      </tr>`,
    )
    .join('')

  const bars = onPath
    .map(
      (n) => `<div class="bar-row">
        <div class="bar-label"><span>${esc(n.label)}</span><span class="muted">${rps(n.capacity)}</span></div>
        <div class="bar-track"><div class="bar-fill" style="width:${Math.min(n.utilization * 100, 100)}%;background:${utilColor(n.utilization)}"></div></div>
        <div class="bar-meta muted"><span>${Math.round(n.utilization * 100)}% at ${g.targetUsers.toLocaleString()} users</span><span>holds ${fmtUsers(n.maxUsers)} users</span></div>
      </div>`,
    )
    .join('')

  const derivations = a.nodes
    .filter((n) => n.capacity != null)
    .map((n) => `<li><b>${esc(n.label)}</b> — ${esc(n.capacityNote)}</li>`)
    .join('')

  const warnings = a.warnings.length
    ? `<section class="avoid-break"><h2>Warnings</h2><ul class="warn">${a.warnings.map((w) => `<li>${esc(w)}</li>`).join('')}</ul></section>`
    : ''

  const figure = diagramDataUrl
    ? `<figure class="diagram avoid-break"><img src="${diagramDataUrl}" alt="Architecture diagram"/><figcaption class="muted">Architecture diagram</figcaption></figure>`
    : ''

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<title>Capacity report — ${esc(name)}</title>
<style>
  @page { size: A4; margin: 16mm 14mm; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    font: 13px/1.55 ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1a2233; background: #fff; -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  .doc { max-width: 760px; margin: 0 auto; padding: 8px; }
  h1 { font-size: 24px; margin: 0 0 2px; }
  h2 { font-size: 15px; margin: 22px 0 8px; padding-bottom: 5px; border-bottom: 1px solid #e3e8f0; }
  .sub { color: #66748c; font-size: 12.5px; margin-bottom: 4px; }
  .muted { color: #66748c; }
  .num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
  header.doc-head { border-bottom: 2px solid #1a2233; padding-bottom: 10px; margin-bottom: 4px; }
  .cards { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 16px 0; }
  .card { border: 1px solid #e3e8f0; border-radius: 10px; padding: 11px 13px; }
  .card .k { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #66748c; }
  .card .v { font-size: 21px; font-weight: 700; margin-top: 3px; }
  .callout { border: 1px solid #f0d4d4; background: #fdf3f3; border-radius: 10px; padding: 11px 13px; margin: 12px 0; }
  .callout .k { font-size: 10px; text-transform: uppercase; letter-spacing: .06em; color: #66748c; }
  .callout .v { font-size: 16px; font-weight: 700; color: #c0392b; margin-top: 2px; }
  ul { margin: 6px 0; padding-left: 20px; }
  li { margin: 3px 0; }
  ul.warn li { color: #8a6d1b; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 6px; }
  th, td { text-align: left; padding: 7px 8px; border-bottom: 1px solid #e8edf4; }
  th { font-size: 10.5px; text-transform: uppercase; letter-spacing: .05em; color: #66748c; border-bottom: 1.5px solid #cdd6e4; }
  th.num { text-align: right; }
  tbody tr:nth-child(even) { background: #f7f9fc; }
  .diagram { margin: 14px 0 4px; text-align: center; }
  .diagram img { max-width: 100%; border: 1px solid #e3e8f0; border-radius: 10px; }
  figcaption { font-size: 11px; margin-top: 5px; }
  .bars { margin-top: 6px; }
  .bar-row { margin: 9px 0; }
  .bar-label { display: flex; justify-content: space-between; font-size: 12px; }
  .bar-track { height: 7px; background: #eef1f6; border-radius: 99px; overflow: hidden; margin: 4px 0; }
  .bar-fill { height: 100%; border-radius: 99px; }
  .bar-meta { display: flex; justify-content: space-between; font-size: 10.5px; }
  .method { color: #3a465c; font-size: 12.5px; }
  footer { margin-top: 26px; padding-top: 10px; border-top: 1px solid #e3e8f0; color: #8a96ad; font-size: 10.5px; }
  .avoid-break { break-inside: avoid; }
  @media screen { body { background: #eef1f6; padding: 20px; } .doc { background: #fff; box-shadow: 0 4px 24px rgba(0,0,0,.12); border-radius: 8px; padding: 28px; } }
</style>
</head>
<body>
<div class="doc">
  <header class="doc-head">
    <h1>Capacity report</h1>
    <div class="sub"><b>${esc(name)}</b> · generated ${esc(generated)}</div>
  </header>

  ${figure}

  <section class="cards avoid-break">
    <div class="card"><div class="k">Max concurrent users</div><div class="v" style="color:#1b5cc4">${fmtUsers(a.maxUsers)}</div></div>
    <div class="card"><div class="k">Peak load @ target</div><div class="v" style="color:#0f8a7e">${rps(a.reachablePeakRps)}</div></div>
    <div class="card"><div class="k">Infra cost</div><div class="v" style="color:#9a7400">$${a.totalMonthlyCost.toLocaleString()}/mo</div></div>
  </section>

  <div class="callout avoid-break">
    <div class="k">Bottleneck</div>
    <div class="v">${esc(a.bottleneckLabel ?? 'No constrained component on the traffic path')}</div>
    <div class="muted" style="font-size:11.5px;margin-top:3px">This component saturates first. Add instances/replicas or raise its limits to lift the system ceiling.</div>
  </div>

  <section class="avoid-break">
    <h2>Workload assumptions</h2>
    <ul>
      <li>Requests/sec per active user: <b>${esc(g.rpsPerUser)}</b></li>
      <li>Peak-to-average multiplier: <b>${esc(g.peakRatio)}×</b></li>
      <li>Write ratio: <b>${Math.round(g.writeRatio * 100)}%</b></li>
      <li>Reference target users: <b>${g.targetUsers.toLocaleString()}</b></li>
    </ul>
    <p class="muted" style="font-size:12px">Peak load at target = ${g.targetUsers.toLocaleString()} users × ${esc(g.rpsPerUser)} × ${esc(g.peakRatio)} = <b>${rps(a.reachablePeakRps)}</b> entering the system.</p>
  </section>

  <section>
    <h2>Per-component analysis</h2>
    <table>
      <thead><tr><th>Component</th><th>Type</th><th class="num">Capacity</th><th class="num">Load @target</th><th class="num">Max users</th><th class="num">Cost/mo</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </section>

  ${onPath.length ? `<section class="avoid-break"><h2>Utilization at ${g.targetUsers.toLocaleString()} users</h2><div class="bars">${bars}</div></section>` : ''}

  <section>
    <h2>How each capacity was derived</h2>
    <ul>${derivations}</ul>
  </section>

  ${warnings}

  <section class="avoid-break">
    <h2>Method</h2>
    <p class="method">Per-user peak demand is propagated from each traffic source through the wired graph. A node passes <i>demand × outflow</i> to its downstream neighbours, so a cache (hit ratio) reduces what reaches the stores behind it. Each node's <i>max users = capacity ÷ per-user demand</i>; the system maximum is the most constrained node on the path (the bottleneck). Figures are planning estimates — measure and load-test before committing budget or hardware.</p>
  </section>

  <footer>Generated by System Designer Studio.</footer>
</div>
</body>
</html>`
}

/** Render an HTML document in an isolated, off-screen iframe and open the print
 *  dialog for it — yielding a clean PDF of just the report. */
export function printReportHtml(html: string): void {
  const iframe = document.createElement('iframe')
  iframe.setAttribute('aria-hidden', 'true')
  Object.assign(iframe.style, {
    position: 'fixed',
    right: '0',
    bottom: '0',
    width: '0',
    height: '0',
    border: '0',
    visibility: 'hidden',
  } as CSSStyleDeclaration)
  document.body.appendChild(iframe)

  const win = iframe.contentWindow
  const doc = iframe.contentDocument || win?.document
  if (!win || !doc) {
    iframe.remove()
    throw new Error('Unable to open print document.')
  }

  const cleanup = () => setTimeout(() => iframe.remove(), 1000)
  const run = () => {
    try {
      win.focus()
      win.onafterprint = cleanup
      win.print()
      // Fallback cleanup if onafterprint never fires (some browsers).
      setTimeout(cleanup, 60_000)
    } catch {
      cleanup()
    }
  }

  doc.open()
  doc.write(html)
  doc.close()

  // Wait for the embedded diagram image (and styles) to load before printing.
  const img = doc.querySelector('img')
  if (img && !img.complete) {
    img.addEventListener('load', () => setTimeout(run, 150))
    img.addEventListener('error', () => setTimeout(run, 150))
  } else {
    setTimeout(run, 250)
  }
}

export function downloadMarkdown(name: string, md: string): void {
  const blob = new Blob([md], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${(name || 'design').toLowerCase().replace(/[^a-z0-9]+/g, '-')}-report.md`
  a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
