import { useStore } from '../store'

export function GlobalsEditor() {
  const globals = useStore((s) => s.globals)
  const setGlobals = useStore((s) => s.setGlobals)

  const rows: { key: keyof typeof globals; label: string; step: number; help: string }[] = [
    { key: 'rpsPerUser', label: 'Req/s per user', step: 0.01, help: 'Average request rate generated by one active user.' },
    { key: 'peakRatio', label: 'Peak multiplier', step: 0.5, help: 'Peak ÷ average traffic (guide: 3–4×).' },
    { key: 'writeRatio', label: 'Write ratio', step: 0.05, help: 'Fraction of requests that are writes.' },
    { key: 'targetUsers', label: 'Target users', step: 1000, help: 'Reference active-user count for the utilization view.' },
  ]

  return (
    <div className="px-4 py-3">
      <div className="text-[10.5px] uppercase tracking-wider text-muted mb-2">Workload assumptions</div>
      <div className="space-y-2">
        {rows.map((r) => (
          <label key={r.key} className="block" title={r.help}>
            <div className="flex items-center justify-between">
              <span className="text-[11.5px] text-ink">{r.label}</span>
              <input
                type="number"
                step={r.step}
                min={0}
                className="w-24 bg-panel2 border border-line rounded-lg px-2 py-1 text-[12px] text-ink text-right focus:outline-none focus:border-accent"
                value={globals[r.key]}
                onChange={(e) => setGlobals({ [r.key]: Number(e.target.value) } as any)}
              />
            </div>
          </label>
        ))}
      </div>
    </div>
  )
}
